### ISSUE TITLE
YAML data

### ISSUE THREAD

**Issue by rcrooks** [spaceinvader021/coral-reef-theme#1]
Hi @spaceinvader021 this is a really nice theme! I just have a small enhancement request: would be nice to have different colors for fields and values in YAML data, since that's used so widely these days. Thanks for considering!

<img width="242" alt="2022-12-17_13-16-21" src="https://user-images.githubusercontent.com/619617/208255879-b4a68827-e834-49bd-b29b-893e3801bf30.png">

**Comment by jtu-hub** [comment]
Thanks @rcrooks for the nice feedback, really appreciate it :) I added it, hope it makes sense to you the way I assigned the colors!
