### ISSUE TITLE
Review C/C++ theme settings

### ISSUE THREAD

**Issue by jtu-hub** [spaceinvader021/coral-reef-theme#2]
Mainly MACROS and CONSTANTS are not properly formatted... General review required, also:
![WhatsApp Bild 2024-04-23 um 13 44 14_13fb6254](https://github.com/jtu-hub/coral-reef-theme/assets/62396490/c6870826-7482-4308-ba81-842d147d62f4)
![WhatsApp Bild 2024-04-23 um 13 43 55_80c340dc](https://github.com/jtu-hub/coral-reef-theme/assets/62396490/bb59d0ff-90c8-45fc-8739-83907cf358e7)
should be:
![WhatsApp Bild 2024-04-23 um 13 44 30_78064c5e](https://github.com/jtu-hub/coral-reef-theme/assets/62396490/2a39e79e-d483-44b0-889f-aaddae88a673)

**Comment by nipanko** [comment]
Hey man 👋. your theme is cool🔥. I didn't find any issue in it. what's this issue about?

**Comment by jtu-hub** [comment]
@nipanko thanks for the nice feedback, really appreciate it ✌🏼 ...The issue is more about finetuning some display settings for C/C++ macros and constants! 🙃

**Comment by jtu-hub** [comment]
fixed with 1.3.2
